export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_SAVED_GAME = 'UPDATE_SAVED_GAME';
export const UPDATE_LOGIN_MESSAGE = 'UPDATE_LOGIN_MESSAGE';
export const START_NEW_GAME = 'START_NEW_GAME';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const UPDATE_TEAM = 'UPDATE_TEAM';
